# Module D: Section 1.1-4 Linear Algebra

## Section 1.1 Introduction

Excerpt from the transcript:

Linear algebra is a field of mathematics that is widely used in various disciplines. Linear algebra plays an important role in data science and machine learning. A solid understanding of linear algebra concepts can enhance the understanding of many data science and machine learning algorithms. This chapter introduces basic concepts for data science and includes vector spaces, orthogonality, eigenvalues, matrix decomposition and further expanded to in-clude linear regression and principal component analysis where linear algebra plays a central role for solving data science problems. More advanced concepts and applications of linear algebra can be found in many references [1, 2, 3, 4]

## 1.2 Elements of Linear Algebra

### 1.2.1 Linear Spaces

#### 1.2.1.1 Linear Combinations

Example 1: Here's an example of swapping the first and third elements of an array using scalars

In [15]:
import numpy as np
x = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
y = ([100.1, 300.3, 700.7])
scalars = np.linalg.solve(x, y)
# Expected output: [700.7 300.3 100.1]
print(scalars)

[700.7 300.3 100.1]


Example 2: Write vector y as a linear combination of vectors (0,1,1), (1,1,0), and (1,0,1)

In [16]:
x = np.array([[0, 1, 1],
              [1, 1, 0],
              [1, 0, 1]])
y = ([100.1, 300.3, 700.7])
scalars = np.linalg.solve(x, y)
# Expected output: [450.45 -150.15  250.25]
print(scalars)

[ 450.45 -150.15  250.25]


### 1.2.2 Orthogonality

Vector 1 is orthogonal to vector 2 if and only if the dot product of v1.v2 is equal to 0. (v1.v2 = v1T v2 = 0).

Example 1: Orthogonal Vector calculation check in Python

In [17]:
# Vectors that are NOT orthogonal
v1 = [[2,-2,3]]
v2 = [[1,5,2]]

v1_transpose = np.transpose(v1)

zero_if_orthogonal = np.dot(v2, v1_transpose)
# Expected output: [[-2]]
print(zero_if_orthogonal)

[[-2]]


In [18]:
# Vectors that ARE orthogonal
v1 = [[1,4,-2]]
v2 = [[2,2,5]]

v1_transpose = np.transpose(v1)

zero_if_orthogonal = np.dot(v2, v1_transpose)
# Expected output: [[0]]
print(zero_if_orthogonal)

[[0]]


### 1.2.4 Eigenvalues and Eigenvectors

For λ to be an eigenvalue, there must be an nonzero eigenvector x = (x1, x2)T such that
Ax = λx

Example 1: Calculate the eigenvalues and eigenvectors for matrix A = [[0,2],[2,3]]

In [19]:
import numpy as np
from numpy.linalg import eig

a = np.array([[0, 2], 
              [2, 3]])
w,v=eig(a)
print('E-value: ', w)
print('E-vector: ', v)

E-value:  [-1.  4.]
E-vector:  [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


Example 2: Compute the eigenvalues and eigenvectors for matrix A = [[2,2,4],[1,3,5],[2,3,5]]

In [20]:
a = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)
print('E-value: ', w)
print('E-vector: ', v)

E-value:  [ 8.80916362  0.92620912 -0.73537273]
E-vector:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


## 1.3 Linear Regression

In [21]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

model = LinearRegression()

model.fit(x, y)

r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('slope:', model.coef_)

new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)

print('slope:', new_model.coef_)

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

coefficient of determination: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]
intercept: [5.63333333]
slope: [[0.54]]
predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


## 1.4 Principal Component Analysis


### 1.4.1 Singular Value Decomposition

Any factorization A = U ∑ V T , with U and V orthogonal and ∑, is called a singular value decomposition SVD of A. The matrices U and V are not unique, but the diagonal entries of ∑ are necessarily the singular values of A. The column of U in such a decomposition are called left singular vectors of A, and the column of V are called right singular vectors of A.

Example 1: SVD of matrix A=[[3,4,3],[2,1,3],[4,2,1]] in Python

In [22]:
import numpy as np

A = [[3,4,3],[1,2,3],[4,2,1]]


u,s,vT = np.linalg.svd(A)

A_check = (u @ np.diag(s) @ vT)

print("Matrix A: ", A)

print("U: ", u)
print("S: ", s)
print("VT: ", v)

print("A Check: ", A_check)

Matrix A:  [[3, 4, 3], [1, 2, 3], [4, 2, 1]]
U:  [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
S:  [7.87764972 2.54031671 0.69958986]
VT:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
A Check:  [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]
